language: python
python:
  - "3.6"      # current default Python on Travis CI

before_install: cd blog

# command to install dependencies
install:
  - pip install -r requirement_dev.txt

  # command to run tests
script:
  - pytest --cov=.