language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
befor_install: cd blog

install:
  - pip install -r requirement_dev.txt
# command to run tests
script:
  - pytest --cov=.