-- MySQL Script generated by MySQL Workbench
-- Tue Oct 20 10:14:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`User` ;

CREATE TABLE IF NOT EXISTS `blog`.`User` (
  `idx` INT NOT NULL,
  `userid` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  PRIMARY KEY (`idx`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`Board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`Board` ;

CREATE TABLE IF NOT EXISTS `blog`.`Board` (
  `idx` INT NOT NULL,
  `title` VARCHAR(100) NULL,
  `content` LONGTEXT NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `User_idx` INT NOT NULL,
  PRIMARY KEY (`idx`),
  INDEX `fk_Board_User_idx` (`User_idx` ASC) VISIBLE,
  CONSTRAINT `fk_Board_User`
    FOREIGN KEY (`User_idx`)
    REFERENCES `blog`.`User` (`idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
